name: Deploy Dev
on:
  push:
    branches:
      - "fix_python_issue"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose stack
        run: docker-compose -f docker-compose.yml up -d
      - name: Check folder
         run: pwd
      -  name: Check files
         run: ls -ltr
